language: python

python:
  - 2.6
  - 2.7

before_install:
  - sudo apt-get install swig

install:
  - pip install --use-mirrors coveralls
  - pip install --use-mirrors nose

script: coverage run --source=nacl setup.py nosetests

after_success:
  coveralls

# vim: set ft=yaml sw=2 sws=2 ts=2 et :
